### ISSUE TITLE
Program doesn't start

### ISSUE THREAD

**Issue by ceraph** [codito/gnome-pomodoro#164]
Distro: Arch
Gnome-Shell: 3.14.2

Executing "gnome-pomodoro" starts some process but no icon appears in the task bar.

**Comment by Jehan** [comment]
Not sure if that's the same thing, but the pomodoro UI does not appear at first plugin activation. I had to at least reload GNOME-shell (with alt-f2 - 'r' for instance) to have the UI appear.
Subsequent GNOME starts are ok. Only the first activation is a problem.

This has been tested with 2 computers (both running the same version of every software below).
Pomodoro 0.11.0-0.2.gitc7ad79d3.fc22 (from the official package of Fedora)
GNOME-shell 3.16.3-1.fc22
Fedora 22.

**Comment by kamilprusko** [comment]
Thanks @Jehan ,

Unfortunately I can't reproduce it on my Fedora 22 :/ and this issue seems to be cropping up... In this version, if there is an error a message dialog should pop up offering to restart gnome-shell... I wonder why it didn't show up.

Did you install / enable other extensions, suspend your system or lock your screen before running "gnome-pomodoro"?

It would be great if you could find something relevant in your logs. For that you may use GNOME Logs app and look for "pomodoro", "gnome-shell", "gnome-session"...

**Comment by Jehan** [comment]
> Unfortunately I can't reproduce it on my Fedora 22

As I said, it seems to happen only the first time. Actually when I first installed it (yesterday), I thought it was just broken. But this morning, booting the laptop, here it was. So when I tried on another computer, the same happened (but this time, I just restarted gnome-shell, and it came up). Now if I just deactivate/reactivate the plugin, it disappear/reappear as expected.
So I feel it's normal that you can't reproduce. Maybe if you were to uninstall, then delete/move all your settings, cache and whatever other data pomodoro creates on the system, then you reinstall and enable it as a fresh user, maybe you can reproduce.

> Did you install / enable other extensions

I have the "Activities Configurator", "Alt Tab Workspace" and "Laine" enabled (I have a bunch other installed, but not activated).

> suspend your system or lock your screen before running "gnome-pomodoro"?

No. Straight install from GNOME Software, then enabled a few secs after.

> It would be great if you could find something relevant in your logs. For that you may use GNOME Logs app and look for "pomodoro", "gnome-shell", "gnome-session"...

I didn't see anything relevant to pomodoro failing to start there. :-/

**Comment by kamilprusko** [comment]
OK, l'l try reproduce it in VM.

Thanks!

**Comment by jumbosushi** [comment]
Similar issue here.
Dist: Ubuntu 16.04LTS
Gnome-shell: 3.18.4

After "gnome-pomodoro" command, the preferenece setting shows up. After I close the popup, the command just hangs there without starting anything.

Could this be since when I installed via sudo apt-get, it asked me to choose a display driver to use and I chose a wrong one? The options were sdb3 or something like lightsdb, and I chose the second one 😓

**Comment by kamilprusko** [comment]
@jumbosushi Looks like you were using other desktop than GNOME, that's a different issue. Current Pomodoro only have an indicator for gnome-shell. Upcoming version will have initial support for Unity and Mate. I'm at doing packaging, it shouldn't take long to a new release.

**Comment by jumbosushi** [comment]
opps my bad. I'm still a linux noob so I wasn't aware that Ubuntu was Unity. Looking forward to the release mate!
