### ISSUE TITLE
Gentoo Ebuild

### ISSUE THREAD

**Issue by lgvo** [codito/gnome-pomodoro#192]
Great tool, GJ.

I have create a gentoo ebuild. [gnome-pomodoro-0.11.0.ebuild](https://github.com/lgvo/dotfiles/blob/master/gentoo/portage/local/gnome-extra/gnome-pomodoro/gnome-pomodoro-0.11.0.ebuild)

I'm not sure if make sense to add to packages, maybe a link to the ebuild on the website may help.
I think I will try to submit to the gentoo at some time.

If you can make a review of the dependencies would be helpful too:
Runtime deps:

> =gnome-base/gnome-common-3.14
> =sys-apps/dbus-1.8.16
> =dev-libs/dbus-glib-0.102
> =gnome-base/gnome-shell-3.16.3
> =dev-libs/gobject-introspection-1.44.0
> =dev-libs/gobject-introspection-common-1.44.0
> =dev-libs/gom-0.3.1
> =media-fonts/droid-113

Compile deps:

> =gnome-base/gnome-common-3.14
> =dev-util/intltool-0.50.2
> =dev-lang/vala-0.26.2

I  haven' t tried yet but I believe it may work without fonts/droid. If so would be nice to make it as a use flag.

Best regards!

**Comment by kamilprusko** [comment]
Thanks! :) Sorry for late response.

Sure I'll ad the instructions on the website :)

Specs in packages directory are used to catch build errors. I use Open Build Service for that and it doesn't support Gentoo, so no reason to include it. It will be easier to maintain the ebuild file in your own repo.

As to your ebuild. The license [should be](https://devmanual.gentoo.org/ebuild-writing/variables/) 

    LICENSE="GPL-3"

I believe you could use [git as a source](https://devmanual.gentoo.org/eclass-reference/git-r3.eclass/index.html), our git repo has branches for each GNOME release. The upside of this is that bugfixes will be available earlier and without any maintanance, the downside is that if there is new release with new dependencies the build might break.

Listed dependencies:

```gnome-shell-3.16.3``` - we just depend on gnome-shell 3.16, no need to specify a point release, in fact the last release works with 3.14 and 3.16

```gom``` - currently isn't used or required, but I'd like to use it in future releases

```droid-fonts``` - yes, it is optional, it's not event widely used - only for screen notifications

Missing dependencies:
```gstreamer gstreamer-plugins-base libcanberra telepathy-glib gtk+-3.0 libgnome-desktop-3.0 desktop-file-utils```

Most dependencies are listed in 
https://github.com/codito/gnome-pomodoro/blob/master/configure.ac

I've compared it with gnome-clocks because it's also a vala-based project
https://sources.gentoo.org/cgi-bin/viewvc.cgi/gentoo-x86/gnome-extra/gnome-clocks/gnome-clocks-3.14.1.ebuild?view=markup

and they include also

    DEPEND="${RDEPEND}
            dev-libs/appstream-glib
            >=dev-util/intltool-0.40.6
            sys-devel/gettext
            virtual/pkgconfig
    "

**Comment by kamilprusko** [comment]
I'll try providing flatpak instead.
