### ISSUE TITLE
Support for Gnome 3.18

### ISSUE THREAD

**Issue by Isgar** [codito/gnome-pomodoro#195]
Manually adding 3.18 to metadata.json makes the icon appear but pressing any button yields:
```
Gjs-Message: JS LOG: Extension "pomodoro@arun.codito.in" had error: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.gnome.Pomodoro exited with status 127
```

(Why do the extensions always break?)

**Comment by kamilprusko** [comment]
Thanks for the info.

It fails at starting a gnome-pomodoro service. You could ```killall gnome-pomodoro``` and run ```gnome-pomodoro``` in terminal to see a more descriptive message.

I've googled this issue seems common after updating libraries if there are API changes like in your case. Reboot seems to solve it, but you may need to recompile gnome-pomodoro... or install a package.

Packages from AUR, our .rpms and all .debs are compiled with ```--as-needed``` flag for the the linker to avoid recompiling.

    LDFLAGS="-Wl,--as-needed" ./configure --disable-static --prefix=/usr --datadir=/usr/share

If you installed a package just try a reboot.

We already have gnome-3.18 branch. As you said, adding "3.18" to metadata.json seems sufficient.

(You can disable gnome-shell checking extensions compatibility. Do it at your own risk ;-))

    $ gsettings set org.gnome.shell disable-extension-version-validation true

**Comment by Isgar** [comment]
Thank you, reinstalling/recompiling the AUR package worked for me, a mere restart did not. And yes, now it works just fine without further modifications.
