### ISSUE TITLE
Why is it needed to chechout the specific branch?

### ISSUE THREAD

**Issue by Tranquility** [codito/gnome-pomodoro#206]
The documentation says I need need to checkout a different branch based on the gnome version I am running. Isn't the master (or even better the released version) compatible with all versions?

**Comment by Tranquility** [comment]
@kamilprusko I am thinking about adding it into the official Gentoo package tree but I would like to know this first.

**Comment by kamilprusko** [comment]
We still make good old [releases](https://github.com/codito/gnome-pomodoro/releases). For instance gnome-3.16 and gnome-3.18 branches contain same release, it's more readable in some cases. A new release usually has support for the last 1-3 GNOME releases.

It is so, because:
* there happen to be breakages in gnome-shell API, for smaller changes we do provide a fallback but may be error-prone for bigger changes
* we take advantages of the new APIs eg. header-bars in GTK+ or gapless playback in gstreamer
* more distros / distro releases supported means I would need to spend more time on testing and I'd rather spend it on software development

Extension needs to be marked as compatible for every major gnome-shell release, so we must follow GNOME release cycle anyway, but same goes for many modern GTK+ apps.
