### ISSUE TITLE
Time to release next minor version? 

### ISSUE THREAD

**Issue by DamienCassou** [codito/gnome-pomodoro#209]
Could you please consider tagging the current commit so packagers like me can rely on it?

**Comment by kamilprusko** [comment]
Hi!

Do you mean to tag development releases? Last tagged version is what I would call latest stable release.

I don't think that **master** is ready for general use or even testing yet. I may not have pushed any commit lately but that's because I've been working on heavier changes. I plan to make next release somewhere around GNOME 3.20 release, which will be on 23 March.

**Comment by DamienCassou** [comment]
fair enough. Thanks
