### ISSUE TITLE
Countdown in indicator

### ISSUE THREAD

**Issue by RichAyotte** [codito/gnome-pomodoro#238]
The countdown in the indicator was a nice feature and I would love to see it come back perhaps as an option.

**Comment by kamilprusko** [comment]
Hi,

You mean the text versions of the indicator?

I can bring it back, but it would be only configurable through gsettings / dconf for now.

**Comment by RichAyotte** [comment]
Yes, that would great. Thank you.

**Comment by kamilprusko** [comment]
Brought it back in eb1f2cdf3eb9db82ed8e49ef2a7b53442d4b27e4

Indicator can be set by

    $ gsettings set org.gnome.pomodoro.plugins.gnome indicator-type text
    $ gsettings set org.gnome.pomodoro.plugins.gnome indicator-type short-text
    $ gsettings set org.gnome.pomodoro.plugins.gnome indicator-type icon

I suppose there should a "Desktop Integration" / "GNOME" section in the preferences window, but I don't want to bloat it... For now I'll keep it hidden and move on to making other features.

**Comment by sajolida** [comment]
I also miss the text indicator as default :)

The new icon indicator looks good but I find it harder to quickly spot how much time is left in my pomodoro (or my break) because the indicator is less visible. It's no big deal but with the text indicator it takes me a blink of an eye to know how much time is left (because my brain is used to read numbers as time) while with the icon indicator it takes me a bit more to locale the indicator (because it's smaller and darker) and then to interpreter its shape it in terms of minutes.

I understand that you don't want to bloat the preferences window, but then maybe this gsettings trick could be mentioned somewhere on the website or in the README for people who wouldn't go read Github or the code to find this out. If you tell me where would be an appropriate place to explain this, I'm ready to submit a patch.

**Comment by poriam** [comment]
@kamilprusko Those `gsetting`s don't work for me. Ubuntu 20.04, gnome-pomodoro 0.16.

**Comment by sojusnik** [comment]
Try `gsettings set org.gnome.pomodoro.plugins.gnome indicator-type 'icon'`
