### ISSUE TITLE
Could not find theme directory

### ISSUE THREAD

**Issue by wnasich** [codito/gnome-pomodoro#272]
When I press the button "Start pomodoro" in the notification popup I got this message:
```
** (gnome-pomodoro:10014): WARNING **: indicator-capability.vala:117: Could not find theme directory "/usr/share/gnome-pomodoro/indicator/XubuntuStudio"
Segmentation fault (core dumped)

```
It is a Lubuntu 16.10

**Comment by kamilprusko** [comment]
Thanks for the report.

I've tried to reproduce it on Ubuntu 16.10 but without luck.

Could you try installing a newer version or provide a fill stack trace of the segfault?

To get the traceback run gnome-pomodoro in terminal

    $ gnome-pomodoro --quit
    $ gdb gnome-pomodoro
    (gdb) run
    (gdb) bt

**Comment by wnasich** [comment]
thanks for you great job!

I'm attaching the backtrace. Have in mind I am running it over Lubuntu (LXDE) .. maybe it is trying to find a file that is not present in my installation. I think It might be a clue. 

[pomodoro-bt.txt](https://github.com/codito/gnome-pomodoro/files/790240/pomodoro-bt.txt)

**Comment by kamilprusko** [comment]
Thanks.

Segfault is triggered while receiving D-Bus message (button click from the notification). I suspect it's either due of messy data from [notification daemon](https://wiki.archlinux.org/index.php/Desktop_notifications) (not sure which Lubuntu uses) or a bug in glib / gio. Pomodoro instead of more common libnotify uses newer [GNotification](https://developer.gnome.org/gio/stable/GNotification.html) API.

I doubt it's a bug in upstream glib (I dont reproduce it in Fedora & GNOME), but you can try running tests

    $ git clone git://git.gnome.org/glib
    $ cd glib
    $ ./autogen.sh
    $ make check

Or try reproducing the crash while running Bustle
![screenshot from 2017-02-21 21-10-50](https://cloud.githubusercontent.com/assets/1135423/23182885/6c106978-f87a-11e6-8a18-abe359c317b6.png)

and see if you have different arguments - then better to report it to notification-daemon.
