### ISSUE TITLE
extensions.gnome.org ?

### ISSUE THREAD

**Issue by porjo** [codito/gnome-pomodoro#296]
When I search for the extension on [extensions.gnome.org](https://extensions.gnome.org/extension/53/pomodoro/) it is listed as not being compatible with my version of gnome!? However, if I install via command line e.g.  `sudo dnf install gnome-shell-extension-pomodoro` it works fine. 

Does extenions website need a newer version?

(I'm using Fedora 25.)

**Comment by kamilprusko** [comment]
The issue is with dependencies. Extension requires a service that's written in Vala. It's binary, and bundling a binary may not work due to linking issues.

Pomodoro evolved from being an extension to an app, but it's hard to perceive it. Skype and Skype extension doesn't have this problem.

The extension should be independent (a separate package / on extensions.gnome.org). Now with flatpak, the extension could just install the missing service from flatpak repo. So Pomodoro may come back on extensions.gnome.org :)

Just need to learn/endure flatpak CLI...

**Comment by porjo** [comment]
My apologies, I just realised that the extensions page has a notice about this! (I didn't see it before)

Thanks, and keep up the good work.
