### ISSUE TITLE
Installation error: expected expression, got '<'

### ISSUE THREAD

**Issue by elieobeid7** [codito/gnome-pomodoro#332]
- Can't install it from gnome-extensions on fedora 27 GNOME Shell 3.26.2,  it says error in red

![screenshot from 2018-01-02 15-04-40](https://user-images.githubusercontent.com/660142/34484607-63b71ee2-efce-11e7-81b3-a3b3e1c9923f.png)

- If I install it using dnf,  it works, but on start up it says

`Extension "pomodoro@arun.codito.in" had error: SyntaxError: expected expression, got '<'`

**Comment by ivankuraj** [comment]
Same here, on Arch Linux installed from AUR:
```
gnome-shell[1237]: Extension "pomodoro@arun.codito.in" had error: SyntaxError: expected expression, g
ot '<'
```
Extension is not usable.

**Comment by 357802** [comment]
Same here. Arch Linux

**Comment by elieobeid7** [comment]
@357802  if you installed it using your package manager, you can uninstall it, if you installed it as a gnome extension, then I have no idea how to uninstall it :)

**Comment by fortime** [comment]
I had encoutered this problem. Finally, I found that it is because we don't have the extension installed from the source code. After the problem started, It will ask us to download the stale extension which causes this error from extensions.gnome.org.
I change this line https://github.com/codito/gnome-pomodoro/blob/fe52244d43cc8fbd0c1752d51693501f3fb32f84/configure.ac#L160 to 
```
if [[ "$datadir/" = "/usr/share/" -o "$datadir" = "/usr/share/local" ]]; then
```
to have the extension installed.
For installing from AUR, we can add a line to PKGBUILD in before running autogen.sh.
```
sed -i "s/\[ \$datadir\/ = \/usr\/share\/\*/[ \"\$datadir\/\" = \"\/usr\/share\/\"/" configure.ac
```

**Comment by SEPIMAGNA** [comment]
gnome-shell-extension.vala:437: Extension error: SyntaxError: expected expression, got '<'
on ubuntu 17.10

**Comment by fmikker** [comment]
I had the same error message every time I logged in on my computer, and the problem was that I had two sets of extensions installed, both via extensions.gnome.org and one via rpm-package.

I moved the folder `~/.local/share/gnome-shell/extensions/pomodoro@arun.codito.in/` to a temporary location and restarted gnome shell and the issue was gone.

**Comment by memeplex** [comment]
I have installed both gnome-pomodoro-git and gnome-shell-pomodoro in Arch Linux and I'm getting this error.

**Comment by mulama77** [comment]
> I had the same error message every time I logged in on my computer, and the problem was that I had two sets of extensions installed, both via extensions.gnome.org and one via rpm-package.
> 
> I moved the folder `~/.local/share/gnome-shell/extensions/pomodoro@arun.codito.in/` to a temporary location and restarted gnome shell and the issue was gone.

The above actually solved the error in Kali linux

**Comment by elieobeid7** [comment]
Let's consider it solved. If anyone has an issue still, I'll reopen it.
