### ISSUE TITLE
Move gnome taskbar icon next to clock

### ISSUE THREAD

**Issue by Susensio** [codito/gnome-pomodoro#467]
This isn't so much an issue but a suggestion / call for help.
As this is a time related extension, I would like to see the icon bar next to the clock instead of stacked with other extensions on the right.

Current behavior:
![current](https://user-images.githubusercontent.com/11474625/77822014-29dc0080-70ef-11ea-944c-fe80e7a5e3ed.png)

Desired behavior:
![desired](https://user-images.githubusercontent.com/11474625/77822016-2ba5c400-70ef-11ea-9c33-37e6daad307f.png)

I've tried modifying the extension myself, following [these instructions from stackoverflow](https://askubuntu.com/questions/453969/how-can-i-order-gnome3-shell-extensions-at-the-top):
 
I've edited `/usr/share/gnome-shell/extensions/pomodoro@arun.codito.in/extension.js`, line 390 from 

```
Main.panel.addToStatusArea(Config.PACKAGE_NAME, this.indicator)
```
to

```
Main.panel.addToStatusArea(Config.PACKAGE_NAME, this.indicator, 0 , Main.panel._centerBox)
```

with any luck.

What am I missing? I would love to see this as an option.

Regards

**Comment by kamilprusko** [comment]
You're close
```
Main.panel.addToStatusArea(Config.PACKAGE_NAME, this.indicator, -1, 'center');
```

It's a valid point but I'm not a fan of it, because:

- In GNOME Shell 3.36 there will be Do Not Disturb icon, so it will not look as clean anymore
![Screenshot from 2020-04-01 18-42-38](https://user-images.githubusercontent.com/1135423/78163445-b0bf0f00-7448-11ea-8b03-f2e22fa36875.png)

- Similar argument could be made whether do you need current time while using a stopwatch? I for one don't like checking time while time-boxing.
- There is a hidden setting to change the indicator icon to text, and both of these customizations will not work together. I'd rather have that option more prominent.
- A single center element in the panel looks clean.

Thanks for the suggestion.
